/*
 * BSD Zero Clause License
 *
 * Copyright (c) 2024-2026 zodac.net
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
 * SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
 * IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

package net.zodac.tracker;

import java.awt.AWTError;
import java.awt.GraphicsEnvironment;
import java.util.logging.Level;
import net.zodac.tracker.app.ScreenshotOrchestrator;
import net.zodac.tracker.framework.ExitState;
import net.zodac.tracker.framework.config.ApplicationConfiguration;
import net.zodac.tracker.framework.config.Configuration;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Main class, which launches the application.
 */
public final class ApplicationLauncher {

    private static final Logger LOGGER = LogManager.getLogger();

    private ApplicationLauncher() {

    }

    /**
     * Main method for the application. Configures any requirements then launches the application.
     *
     * @see ScreenshotOrchestrator
     */
    // TODO: Investigate whether it's worth not logging out
    static void main() {
        checkDisplay();
        setupApplication();
        startApplication();
    }

    private static void checkDisplay() {
        final String display = System.getenv("DISPLAY");
        if (display == null || display.isBlank()) {
            LOGGER.error("Environment variable 'DISPLAY' is not configured");
            exit(ExitState.FAILURE);
        }

        try {
            final GraphicsEnvironment _ = GraphicsEnvironment.getLocalGraphicsEnvironment();
        } catch (final AWTError e) {
            LOGGER.debug("Unable to connect to X11 display '{}'", display, e);
            LOGGER.error("Unable to connect to X11 display '{}'", display);
            exit(ExitState.FAILURE);
        }
    }

    private static void setupApplication() {
        try {
            // Suppress warnings generated by the Selenium library (which uses JUL)
            final java.util.logging.Logger seleniumLogger = java.util.logging.Logger.getLogger("org.openqa.selenium");
            seleniumLogger.setLevel(Level.SEVERE);

            // Validate that the application configuration is valid
            final ApplicationConfiguration _ = Configuration.get();
        } catch (final ExceptionInInitializerError e) {
            LOGGER.debug("Invalid environment variable", e);
            LOGGER.error("Invalid environment variable: {}", e.getCause() == null ? e.getMessage() : e.getCause().getMessage());
            exit(ExitState.FAILURE);
        } catch (final Exception e) {
            LOGGER.debug("Unexpected error starting application pre-requisites", e);
            LOGGER.error("Unexpected error starting application pre-requisites: {}", e.getMessage());
            exit(ExitState.FAILURE);
        }
    }

    private static void startApplication() {
        try {
            final ExitState exitState = ScreenshotOrchestrator.start();
            exit(exitState);
        } catch (final Exception e) {
            LOGGER.debug("Error abruptly ended execution", e);
            LOGGER.error("Error abruptly ended execution: {}", e.getMessage());
            exit(ExitState.FAILURE);
        }
    }

    private static void exit(final ExitState exitState) {
        System.exit(exitState.exitCode()); // NOPMD: DoNotTerminateVM - happy to terminate here
    }
}
