name: Docker CI

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/docker.yml'
      - 'ci/docker/.hadolint.yaml'
      - 'docker/Dockerfile'
      - 'docker/entrypoint.sh'
      - 'docker/start.sh'
  workflow_dispatch: # allows manual trigger

jobs:
  analyze:
    name: Docker Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      # Docker linting
      - name: Run Hadolint and generate report
        uses: hadolint/hadolint-action@v3.3.0
        with:
          config: ./ci/docker/.hadolint.yaml
          dockerfile: docker/Dockerfile
          output-file: hadolint-report.json

      - name: Upload Hadolint report
        if: failure()
        uses: actions/upload-artifact@v7.0.1
        with:
          name: hadolint-report
          path: hadolint-report.json
          overwrite: true
          retention-days: 1
